import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const envFile = resolve('.env');

if (existsSync(envFile)) {
  process.loadEnvFile(envFile);
}

const sameOrigin = process.argv.includes('--same-origin');
const chatServerUrl = sameOrigin
  ? ''
  : (process.env.CHAT_SERVER_URL || '').replace(/\/$/, '');
const googleMapsApiKey = process.env.GOOGLE_MAPS_API_KEY || '';

if (chatServerUrl) {
  const chatUrl = new URL(chatServerUrl);
  const loopback = ['localhost', '127.0.0.1', '::1'].includes(chatUrl.hostname);

  if (chatUrl.origin !== chatServerUrl || (chatUrl.protocol !== 'https:' && !loopback)) {
    throw new Error(
      'CHAT_SERVER_URL must be an HTTPS origin, except for local development.',
    );
  }
}

writeFileSync(
  resolve('src/app/generated-config.ts'),
  `// Generated by scripts/config.mjs. This value is public browser configuration.\n` +
    `export const CHAT_SERVER_URL = ${JSON.stringify(chatServerUrl)};\n` +
    `export const GOOGLE_MAPS_API_KEY = ${JSON.stringify(googleMapsApiKey)};\n`,
);

console.info('Prepared public browser configuration.');